---
title: "A Beginner's Guide to scRNAseq - GI Edition"
author: "CDN team"
date: last-modified
date-format: "[Last compiled on] D MMMM, YYYY"
format:
  html:
    toc: true
    toc_float: true
    toc-location: left
    toc-depth: 4
    html-math-method: katex
    embed-resources: true
    self-contained-math: true
editor_options: 
  chunk_output_type: inline
---

## Day 1: Tue May 27th 2025

-   **Where**: Karp 6 Conference Room
-   **Course Material**:
    -   [Introduction to R/Rstudio/Seurat](http://htmlpreview.github.io/?https://github.com/CellDiscoveryNetwork/beginner-workshop-gi-5-25/blob/main/day-1/1%20-%20Introduction.pdf) [[Recording](https://drive.google.com/file/d/1HoIPLuOT6bteMIPsGSaUd_Pzj0ipcDrI/view?usp=sharing)]
        -   How to navigate Rstudio
        -   Fundamentals and data wrangling in R
        -   Working with a Seurat object
    -   [Basic sc-RNAseq workflow](http://htmlpreview.github.io/?https://github.com/CellDiscoveryNetwork/beginner-workshop-gi-5-25/blob/main/day-1/2-The%20Basic%20scRNAseq%20Analysis%20Workflow.pdf) [[Recording](https://drive.google.com/file/d/1klrojhzCc-_YRzyqGbLETVEwGAu1cK3J/view?usp=sharing)]
        -   Main steps for scRNAseq workflow
        -   Intuition behind each step
    -   [Data Download](http://htmlpreview.github.io/?https://github.com/CellDiscoveryNetwork/beginner-workshop-gi-5-25/blob/main/day-1/3-download-data.html) [[Recording](https://drive.google.com/file/d/1MHB6Dwqf-i2wqETa4aEqYoRXI3x-mVV0/view?usp=sharing)]
        - Download the data needed for this workshop
        - Go over the basics of a Seurat object
    -   [Normalization & HVG selection](http://htmlpreview.github.io/?https://github.com/CellDiscoveryNetwork/beginner-workshop-gi-5-25/blob/main/day-1/4-norm-hvg.html) [[Recording](https://drive.google.com/file/d/1ZtPreTDYu2FsXWEi_2RMPLFcqQPdJ4Tr/view?usp=sharing)]
        -   Why and how to normalize sc-RNAseq data
        -   Why and how to select highly variable genes
    -   [Quality Control](http://htmlpreview.github.io/?https://github.com/CellDiscoveryNetwork/beginner-workshop-gi-5-25/blob/main/day-1/5-QC.html) [[Recording](https://drive.google.com/file/d/1lxRTcX0LL7AkSSpLlU2Sa54C6yLgBERf/view?usp=sharing)]
        -   How to carry out QC analysis
        -   What parameters do we need to look at and how to interpret them
        -   Computing doublet scores
        -   Tips and tricks during the QC process

## Day 2: Tue June 3rd 2025

-   **Where**: Karp 6 Conference Room
-   **Course Material**:
    -   [PCA, Integration & KNN graphs](http://htmlpreview.github.io/?https://github.com/CellDiscoveryNetwork/beginner-workshop-gi-5-25/blob/main/day-2/6-PCA_Harmony_kNN.html) [[Recording](https://drive.google.com/file/d/1b4n1zYj3s9r-BWosw-q70rtPLNSoP3su/view?usp=sharing)]
        -   Brief overview on PCA and how to use it for sc-RNAseq
        -   KNN-graph representation of the data
        -   Correcting batch effects with Harmony
    -   [Clustering](http://htmlpreview.github.io/?https://github.com/CellDiscoveryNetwork/beginner-workshop-gi-5-25/blob/main/day-2/7-Clustering.html) [[Recording](https://drive.google.com/file/d/10T0ompobzsXZPsKcPFtUIO36XwOS_1Eo/view?usp=sharing)]
        -   How to cluster sc-RNAseq data
        -   What algorithms can we use
        -   How to assess if a clustering resolution is good
    -   [Differential Gene Expression & Level 1 Annotation](http://htmlpreview.github.io/?https://github.com/CellDiscoveryNetwork/beginner-workshop-gi-5-25/blob/main/day-2/8-dge-annotlvl1.html) [[Recording](https://drive.google.com/file/d/1fB1_jWP3HzvUOuo2XEofpWJiFgbAE2Tr/view?usp=sharing)]
        -   How to compute differentially expressed genes between clusters
        -   How to evaluate differential expression statistics
        -   Reference-based cell type annotation
        -   Manual cell type annotation
    -   [Subclustering & Level 2 Annotation](http://htmlpreview.github.io/?https://github.com/CellDiscoveryNetwork/beginner-workshop-gi-5-25/blob/main/day-2/9-compositional_analysis.html) [[Recording](https://drive.google.com/file/d/1Nz1A-8oZI70amAGsawWATdeKo8Ft6hU9/view?usp=sharing)]
        -   What does level 2 annotation mean and why we need it
        -   How to iteratively annotate a dataset

### Exit Forms
[Day 1](https://forms.gle/273toLmTTmQ7GBsX7) 

[Day 2](https://forms.gle/vhKtAa3fiPqEk5me6)
